### PR TITLE
Fix mismatch between UDC totalDeposit and effectiveBalance

### LINKED ISSUE #2275: MetaMask - RPC Error: execution reverted: deposit not increasing
## Steps to Reproduce
1. Deposit tokens to the UDC 
udc_deposit_screen

2. Withdraw tokens from the UDC. They would get withdrawn to the raiden account. These tokens are kept as it is in the raiden account.

3. Again deposit to the UDC. The UDC has 0 SVT token balance(because we just withdrew in the previous step).
 
execution_reverted_deposit_not_increasing

## Expected Result
- Ideally the user should be able to deposit and withdraw tokens as he wishes.

## Actual Result
 ```
inpage.js:1 MetaMask - RPC Error: execution reverted: deposit not increasing {code: -32603, message: "execution reverted: deposit not increasing", data: {…}}
```

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

### PR DESCRIPTION
**Pull request by andrevmatos**
**Thank you for submitting this pull request :)**

Fixes #2275

**Short description**
`udcDeposit` actions contained `totalDeposit` as sole `meta` property, but it actually was the `effectiveBalance` value, which raised issues when calculating the new totalDeposit when making a deposit after a withdraw was performed.
This PR fixes it by using actual `totalDeposit` as meta value (for linking `udcDeposit` requests & success/failure responses), and added `balance` to payload, to be used as UDC balance, instead of the deposit.
Integration tests were extended to assert behavior when depositing after withdraw, which works as regression test for this action.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.
2.

### CODE REVIEW

File: raiden-ts/src/services/epics.ts [hunk 1]
```diff
@@ -459,13 +459,16 @@ export function monitorUdcBalanceEpic(
        * etc), but merged on the top-level observable, therefore connectivity issues can cause
        * exceptions which would shutdown the SDK. Let's swallow the error here, since this will be
        * retried on next block, which should only be emitted after connectivity is reestablished */
-      defer(
```
Comment (palango) [inline raiden-ts/src/services/epics.ts:462]: Regarding line 455: We should open an issue for the contracts to add events.

**Review by palango — APPROVED** [review]
Looks good.
