### PR TITLE
dApp: displays RDN on the Withdrawal screen

### LINKED ISSUE #2237: RDN tokens not shown on the token withdrawal screen on mainnet
## Thanks for filing a bug report :-)

Reported by @jjjseee

## Steps to Reproduce
1. Deposit RDN to the UDC
2. Withdraw tokens from the UDC
3. Wait 100 blocks
4. Check etherscan if the withdraw-transaction has been completed for the Raiden Account (in this case: https://etherscan.io/tx/0x9aa881340667f0d81c9e1b5c25e963c38b30e4be5b58aa500a42471957b95a66)

## Expected Result
- I see the RDN tokens on the Withdrawal Screen and can withdraw them to the main account.

## Actual Result
- I don't see the tokens on the withdrawal screen and cannot withdraw the tokens.

   grafik

### PR DESCRIPTION
**Pull request by taleldayekh**
Fixes #2237 

**Short description**
This PR fixes issue with RDN not getting displayed on the Withdrawal screen.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Withdraw RDN from the UDC dialog, wait for 100 blocks.
2. The withdrawn RDN amount should now be available for withdrawal from the Withdrawal screen.

### CODE REVIEW

File: raiden-dapp/src/services/raiden-service.ts [hunk 1]
```diff
@@ -669,7 +670,11 @@ export default class RaidenService {
     if (!raiden.mainAddress) {
       return [];
     }
-    const allTokens = await raiden.getTokenList();
+    const allTokenAddresses = uniq(
+      (await raiden.getTokenList()).concat(
```
Comment (andrevmatos) [inline raiden-dapp/src/services/raiden-service.ts:674]: Can you get this list from somewhere else? Maybe `store.getters.tokens.map(token => token.address)`. `getTokenList` scans the blockchain, so it's slow, and since this was already done to fetch the tokens on initialization, you may just populate it from there.

Comment (taleldayekh) [reply raiden-dapp/src/services/raiden-service.ts:674]: Ah, ok I see.

Comment (taleldayekh) [reply raiden-dapp/src/services/raiden-service.ts]: `store.getters.tokens` just returns an empty array. But I removed that code from the `raiden-service` and I do all the work in the `Withdrawal.vue` component now.

File: raiden-dapp/src/components/account/Withdrawal.vue [hunk 2]
```diff
@@ -156,15 +154,24 @@ export default class Withdrawal extends Mixins(BlockieMixin) {
...
-
-    if ((this.udcToken.balance as BigNumber).gt(Zero)) {
-      this.balances = uniqBy(
-        [...this.balances].concat(this.udcToken),
-        (token) => token.address
-      );
-    }
+    const balancesWithoutMainnetUtilityToken = await this.$raiden.getRaidenAccountBalances();
+    const balancesWithMainnetUtilityToken = uniqBy(
+      [...balancesWithoutMainnetUtilityToken].concat(this.udcToken),
```
Comment (andrevmatos) [inline raiden-dapp/src/components/account/Withdrawal.vue:159]: You don't need to spread the original array, it's ephemeral anyway, and also `concat` doesn't mutate the arrays.

File: raiden-dapp/src/components/account/Withdrawal.vue [hunk 3]
```diff
@@ -156,15 +154,24 @@ export default class Withdrawal extends Mixins(BlockieMixin) {
...
   async mounted() {
-    this.balances = await this.$raiden.getRaidenAccountBalances();
-
-    if ((this.udcToken.balance as BigNumber).gt(Zero)) {
-      this.balances = uniqBy(
-        [...this.balances].concat(this.udcToken),
-        (token) => token.address
-      );
-    }
+    const balancesWithoutMainnetUtilityToken = await this.$raiden.getRaidenAccountBalances();
```
Comment (andrevmatos) [inline raiden-dapp/src/components/account/Withdrawal.vue:157]: These var names are not good: you can't be sure mainnet SVT won't come on this list. It just doesn't right now, but could if TN deployment is enabled there.

File: raiden-dapp/src/components/account/Withdrawal.vue [hunk 4]
```diff
@@ -156,15 +154,24 @@ export default class Withdrawal extends Mixins(BlockieMixin) {
...
+    const balancesWithMainnetUtilityToken = uniqBy(
+      [...balancesWithoutMainnetUtilityToken].concat(this.udcToken),
+      (token) => token.address
+    );
+    const updatedBalances = await Promise.all(
+      balancesWithMainnetUtilityToken.map(async (token) => ({
+        ...token,
+        balance: await this.$raiden.raiden.getTokenBalance(
```
Comment (andrevmatos) [inline raiden-dapp/src/components/account/Withdrawal.vue:165]: Accessing `$raiden.raiden` isn't a good practice here: since we have `RaidenService`, it should wrap all accesses to the `Raiden` SDK instance. You may expose it, or the function to get all tokens balances, maybe with a flag for either main account or raiden account, and use it from there.

Comment (taleldayekh) [reply raiden-dapp/src/components/account/Withdrawal.vue:165]: Yes, I changed that already. :)

File: raiden-dapp/src/services/raiden-service.ts [hunk 5]
```diff
@@ -708,8 +708,14 @@ export default class RaidenService {
...
-    const tokenBalance = await this.raiden.getTokenBalance(tokenAddress);
+  async getTokenBalance(
+    tokenAddress: string,
+    raidenAccount?: string
+  ): Promise<string> {
+    const tokenBalance = await this.raiden.getTokenBalance(
+      tokenAddress,
+      raidenAccount
+    );
     return tokenBalance.toString();
```
Comment (andrevmatos) [inline raiden-dapp/src/services/raiden-service.ts:719]: You sure you want to convert it `toString()`? You need to convert it right after to BigNumber again just to compare.. maybe it'd be better to leave it as a BigNumber, and then to convert only where you need to use it as a string

Comment (taleldayekh) [reply raiden-dapp/src/services/raiden-service.ts:719]: It was being converted to a string initially, I didn't change that. But I can check if not converting it breaks anything, if not I can make it a BigNumber.

Comment (taleldayekh) [reply raiden-dapp/src/services/raiden-service.ts:719]: Yeah, it breaks something in the transfer route component. I'll take a look at that after I've fixed all broken tests for withdrawal.

Comment (taleldayekh) [reply raiden-dapp/src/services/raiden-service.ts]: Returning it as a `BigNumber` now.

File: raiden-dapp/src/components/account/Withdrawal.vue [hunk 6]
```diff
@@ -142,29 +141,37 @@ import { BigNumber } from 'ethers/utils';
...
-    ...mapGetters(['udcToken']),
+    ...mapState(['raidenAccountBalance']),
+    ...mapGetters(['udcToken', 'allTokens']),
   },
 })
 export default class Withdrawal extends Mixins(BlockieMixin) {
-  tokens!: Tokens;
-  raidenAccountBalance!: string;
+  allTokens!: Token[];
+  raidenAccountBlanace!: string;
```
Comment (andrevmatos) [inline raiden-dapp/src/components/account/Withdrawal.vue:150]:
```suggestion
  raidenAccountBalance!: string;
```

**Review by andrevmatos — APPROVED** [review]
lgtm, ty
