### PR TITLE
sdk: Fix nonce race when open+approve concurrently with Wallet

### LINKED ISSUE #1830: CLI- opening channel fails
## Steps to Reproduce
1. Build cli and try to open a channel
2. `http PUT localhost:5001/api/v1/channels partner_address=0x002857f3a3BEa9DC0301D6DCf573692720f88B5a total_deposit=100000 token_address=0x59105441977ecD9d805A4f5b060E34676F50F806`

## Expected Result
- 200 Response

## Actual Result
```
pi@NanoPi-Duo2:~/light-client$ http PUT localhost:5001/api/v1/channels partner_address=0x002857f3a3BEa9DC0301D6DCf573692720f88B5a total_deposit=100000 token_address=0x59105441977ecD9d805A4f5b060E34676F50F806
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 148
Content-Security-Policy: default-src 'none'
Content-Type: text/html; charset=utf-8
Date: Mon, 29 Jun 2020 16:12:17 GMT
X-Content-Type-Options: nosniff
X-Powered-By: Express

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```

## Additional Infos (Optional) 

My nodes address: https://goerli.etherscan.io/address/0x00d384ef74575e97884215e9f39142228c7acfa8

[Full log files](https://github.com/raiden-network/light-client/files/4846767/raiden.zip)
There's a lot of trash in the logs (check out the last 20 minutes of the logfile. I also tried multiple other requests.
The right part should be:
```
Jun 29 16:09:44 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959475 } }
Jun 29 16:10:00 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959476 } }
Jun 29 16:10:12 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959477 } }
Jun 29 16:10:28 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959478 } }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   type: 'token/monitored',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   payload: {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     token: '0x59105441977ecD9d805A4f5b060E34676F50F806',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     fromBlock: 2723614
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   type: 'token/monitored',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   payload: {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     token: '0x59105441977ecD9d805A4f5b060E34676F50F806',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     fromBlock: 2723615,
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     toBlock: 2959478
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   type: 'channel/open/request',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   payload: { settleTimeout: undefined, deposit: e { _hex: '0x0186a0' } },
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   meta: {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     partner: '0x002857f3a3BEa9DC0301D6DCf573692720f88B5a'
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   type: 'channel/deposit/failure',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   payload: Error: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing t
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at m (/home/pi/light-client/raiden-cli/build/bundle.js:82:283353)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at t.XMLHttpRequest.s.onreadystatechange (/home/pi/light-client/raiden-cli/build/bundle.js:82:281777)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at t.XMLHttpRequest.dispatchEvent (/home/pi/light-client/raiden-cli/build/bundle.js:373:5991)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at b (/home/pi/light-client/raiden-cli/build/bundle.js:373:6177)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at IncomingMessage.<anonymous> (/home/pi/light-client/raiden-cli/build/bundle.js:373:3744)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at IncomingMessage.emit (events.js:322:22)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at endReadableNT (_stream_readable.js:1187:12)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     code: -32010,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     data: undefined,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     url: 'http://parity.goerli.ethnodes.brainbot.com:8545',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     body: '{"method":"eth_sendRawTransaction","params":["0xf8a81d847735940082abef9459105441977ecd9d805a4f5b060e34676f50f80680b844095ea7b30000000000000000000000003ea2a
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     responseText: '{"jsonrpc":"2.0","error":{"code":-32010,"message":"Transaction gas price supplied is too low. There is another transaction with same nonce in the q
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     transaction: {
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       nonce: 29,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       gasPrice: [e],
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       gasLimit: [e],
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       to: '0x59105441977ecD9d805A4f5b060E34676F50F806',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       value: [e],
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       data: '0x095ea7b30000000000000000000000003ea2a1fed7fdef300da19e97092ce8fdf8bf66a300000000000000000000000000000000000000000000000000000000000186a0',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       chainId: 5,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       v: 46,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       r: '0x600fa48354d67b0b989565e6e64487e002b41205bef6b72ca8cf9e9d89da3946',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       s: '0x05045c8084992e48df1db4db6334afdab4eea6cdc620e6b5f7595c6f292a82b6',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       from: '0x00D384EF74575E97884215e9f39142228c7ACfa8',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       hash: '0x1f233f6a33060a00a8091b1cd5715a339c0e89a95cce0a6941f30970dce78b44'
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     },
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     transactionHash: '0x1f233f6a33060a00a8091b1cd5715a339c0e89a95cce0a6941f30970dce78b44'
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   },
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   meta: {
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     partner: '0x002857f3a3BEa9DC0301D6DCf573692720f88B5a'
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   },
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   error: true
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]: (node:3133) UnhandledPromiseRejectionWarning: Error: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increas
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at m (/home/pi/light-client/raiden-cli/build/bundle.js:82:283353)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at t.XMLHttpRequest.s.onreadystatechange (/home/pi/light-client/raiden-cli/build/bundle.js:82:281777)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at t.XMLHttpRequest.dispatchEvent (/home/pi/light-client/raiden-cli/build/bundle.js:373:5991)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at b (/home/pi/light-client/raiden-cli/build/bundle.js:373:6177)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at IncomingMessage.<anonymous> (/home/pi/light-client/raiden-cli/build/bundle.js:373:3744)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at IncomingMessage.emit (events.js:322:22)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at endReadableNT (_stream_readable.js:1187:12)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]: (node:3133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]: (node:3133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.
Jun 29 16:10:44 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959479 } }
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959480 } }
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   type: 'channel/open/success',
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   payload: {
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     id: 3063,
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     token: '0x59105441977ecD9d805A4f5b060E34676F50F806',
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     settleTimeout: 500,
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     isFirstParticipant: true,
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     txHash: '0xedfb0191a1f3f007365987d975bc86c7da9d797b98fb5ca6dbae23a96e466b7c',
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     txBlock: 2959480,
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     confirmed: undefined
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   },
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   meta: {
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     partner: '0x002857f3a3BEa9DC0301D6DCf573692720f88B5a'
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   }
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:11:16 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959481 } }
Jun 29 16:11:28 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959482 } }
Jun 29 16:11:44 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959483 } }
```

## Remarks
It looks to me as if the SDK tries to use the same nonce for deposit as it used for the openChannel Tx.
CC @weilbith - we briefly talked about the issue

### PR DESCRIPTION
**Pull request by andrevmatos**
Fixes #1830

**Short description**
See https://github.com/raiden-network/light-client/issues/1830#issuecomment-651249481

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Bug: test it doesn't happen anymore

### CODE REVIEW

File: raiden-ts/src/channels/epics.ts [hunk 1]
```diff
@@ -595,21 +595,23 @@ export const channelMonitoredEpic = (
   );
 
 const makeDeposit$ = (
-  tokenContract: HumanStandardToken,
-  tokenNetworkContract: TokenNetwork,
-  sender: Address,
-  address: Address,
-  partner: Address,
+  [tokenContract, tokenNetworkContract]: [HumanStandardToken, TokenNetwork],
+  [sender, address, partner]: [Address, Address, Address],
```
Comment (weilbith) [inline raiden-ts/src/channels/epics.ts:599]: Not actually part of this PR so feel free to ignore it.
I think the parameter `address` is not well named. In fact the first 5 parameter are all different Ethereum addresses. So I basically have no idea what `address` should be here. I have to go back to check the call references of this function. Even there the variable is just called `address`. Happily this function (was `channelOpenEpic`) is just forwarding this parameter and has a description for it:  `Our address`. I think this could become improved. But as I said maybe not here.

File: raiden-ts/src/channels/epics.ts [hunk 2]
```diff
@@ -595,21 +595,23 @@ export const channelMonitoredEpic = (
...
 ): Observable<channelDeposit.failure> => {
   if (!deposit?.gt(Zero)) return EMPTY;
   return defer(() => tokenContract.functions.allowance(sender, tokenNetworkContract.address)).pipe(
     mergeMap((allowance) =>
       allowance.gte(deposit)
         ? of(true)
-        : from(tokenContract.functions.approve(tokenNetworkContract.address, deposit)).pipe(
+        : from(
+            tokenContract.functions.approve(tokenNetworkContract.address, deposit, {
+              nonce: approveNonce,
```
Comment (weilbith) [inline raiden-ts/src/channels/epics.ts:612]: Just to make sure: if `approveNonce` is `undefined` it gets ignored and the auto-nonce mechanism works as before? I assume so. But sometimes library implementations are special. Better safe than sorry...

File: raiden-ts/src/channels/epics.ts [hunk 3]
```diff
@@ -727,14 +729,12 @@ export const channelOpenEpic = (
                 // errors on makeDeposit$ are handled independently and don't fail open request
                 // but the channelDeposit.failure action may be fired
                 makeDeposit$(
-                  tokenContract,
-                  tokenNetworkContract,
-                  onchainAddress,
-                  address,
-                  partner,
+                  [tokenContract, tokenNetworkContract],
```
Comment (weilbith) [inline raiden-ts/src/channels/epics.ts:732]: I basically don't car too much. But because I'm curious I ask: what is your advantage of grouping these parameters into arrays? :thinking:

File: raiden-ts/tests/unit/epics/channels.spec.ts [hunk 4]
```diff
@@ -408,7 +408,9 @@ describe('channelDepositEpic', () => {
       channelDeposit.failure(expect.any(Error), { tokenNetwork, partner: partner.address }),
     );
     expect(tokenContract.functions.approve).toHaveBeenCalledTimes(1);
-    expect(tokenContract.functions.approve).toHaveBeenCalledWith(tokenNetwork, deposit);
+    expect(tokenContract.functions.approve).toHaveBeenCalledWith(tokenNetwork, deposit, {
```
Comment (weilbith) [inline raiden-ts/tests/unit/epics/channels.spec.ts:411]: Actually there is a case for the manual nonce missing. :stuck_out_tongue_winking_eye:

**Comment by weilbith** [comment]
I attempt to do a quick test with the Ethereum node that cause the issue so see if it actually works.

**Comment by weilbith** [comment]
I tested it locally with our internal Parity node for Goerli  (the exact same one that Oliver used). It works. :tada:

File: raiden-ts/src/channels/epics.ts (hunk 1 above)
Comment (andrevmatos) [reply raiden-ts/src/channels/epics.ts:599]: Well, the first 2 parameters are actually `Contract` instances, not Addresses. I agree with you, the name can be improved, but this name come from the epics dependencies `RaidenEpicDeps`, used like that all across the SDK, so it already became a common usecase, and the root for it is that it makes pair with the `Signer` instances: you'll find a `signer` and an `address` on the `deps` directly, which are the actual/effective signer and respective address, and `main: { signer: Signer; address: Address }`, which belongs to the main account, if used. The first Address parameter here actually is the `address` of the `main` account (or dupe of the `address`, if subkey isn't set), as we need to know which allowance to check.

File: raiden-ts/src/channels/epics.ts (hunk 2 above)
Comment (andrevmatos) [reply raiden-ts/src/channels/epics.ts:612]: Yes, exactly, this is actually the case with the norma `channelDeposit.request`, since it shouldn't race there, so needed only here because of the concurrent `channelOpen`  call.

File: raiden-ts/src/channels/epics.ts (hunk 3 above)
Comment (andrevmatos) [reply raiden-ts/src/channels/epics.ts:732]: Just to reduce the number of parameters on the function, and aggregate them when it makes sense. It actually just look like an Array, but works like a tuple, first of the 2 contracts, and then of the 3 addresses.

Comment (weilbith) [reply raiden-ts/src/channels/epics.ts:736]: If you like it. :shrug:
