### PR TITLE
Delay non-closing auto-settle to prevent wasted gas on channelSettle race

### LINKED ISSUE #2798: Offset `settle` calls from channel partners
When closing a channel and reaching the end of the settlement window, both channel partners will send a settlement transaction to the blockchain.

As those coincide, only one will go through, while one will be rejected. This could be observed while running the BF1 scenario.

- Successful tx: https://etherscan.io/tx/0x08d7125341f12b114d128271f9b37cc4645d825656bee8dc284655e88c083e8b
- Failed tx: https://etherscan.io/tx/0x55ac81644439c97447b8bd10c67f6c616e1fdfe6f2ee8c8e46e80739e171eaff

To limit failing transaction we could offset the transactions ending by the partner with the higher address by a number of blocks.

### PR DESCRIPTION
**Pull request by andrevmatos**
Fixes #2798 

**Short description**
Optimization: auto-settling peers have shifted timeouts after settleable block; closing side is expected to auto-settle only `confirmationBlocks=5` after channel becomes settleable; if it doesn't, non-closing side auto-settle is delayed to `revealTimeout=50` blocks; unless partner is a PC, which always settle early, so in this case LC always wait longer before attempting auto-settling.
This tries to prevent both clients calling `settleChannel` at the same time and one of them wasting the gas, as only one of the txs will succeed.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.
2.

### CODE REVIEW

File: raiden-ts/src/channels/epics/settle.ts [hunk 1]
```diff
@@ -66,56 +67,56 @@ export function channelSettleableEpic(
...
+      { blockNumber, channels },
+      presences,
+      { confirmationBlocks, revealTimeout },
+    ]) {
+      for (const channel of Object.values(channels)) {
+        if (channel.state !== ChannelState.settleable) continue;
+
+        const partnerIsOnlineLC =
+          channel.partner.address in presences &&
+          !getCap(presences[channel.partner.address]?.payload.caps, Capabilities.DELIVERY);
```
Comment (palango) [inline raiden-ts/src/channels/epics/settle.ts:101]: Do we have such checks (having delivery cap on signals python client) in other places? If so, we should factor them out into one place.

Comment (andrevmatos) [reply raiden-ts/src/channels/epics/settle.ts:101]: Yes, I think in one other place. I'll make a new commit to split this out in a separate function.

File: raiden-ts/src/channels/epics/settle.ts [hunk 2]
```diff
@@ -66,56 +67,56 @@ export function channelSettleableEpic(
...
+
+        /* iff we are *sure* partner will wait longer (i.e. they're a LC and *we* are the closing
+         * side), then we autoSettle early; otherwise (it's a PC or they're the closing side),
+         * we can wait longer before autoSettling */
+        let waitConfirmations: number;
+        if (partnerIsOnlineLC && channel.closeParticipant === address)
+          waitConfirmations = confirmationBlocks;
+        else waitConfirmations = revealTimeout;
```
Comment (palango) [inline raiden-ts/src/channels/epics/settle.ts:109]: Shouldn't this be `revealTimeout + confirmationBlocks`?

**Review by palango — APPROVED** [review]
Great, simple solution. 

LGTM after the small refactoring.

File: raiden-ts/src/channels/epics/settle.ts (hunk 2 above)
Comment (andrevmatos) [reply raiden-ts/src/channels/epics/settle.ts:105]: No need.. `revealTimeout` is just a bigger value than `confirmationBlocks`, to shift the delay; no need to _confirm_ it

File: raiden-ts/src/channels/epics/settle.ts (hunk 1 above)
Comment (andrevmatos) [reply raiden-ts/src/channels/epics/settle.ts]: :heavy_check_mark:
