### PR TITLE
Fix received transfers not showing up on history

### LINKED ISSUE #1503: Received transfers aren't shown on transfers history
This actually isn't a dApp issue, but after receiving got merged, as it wasn't enabled by default anywhere, I forgot to expose the received transfers through `Raiden.transfers$` observable. Also, a proper transfer id/unique key is needed, since outgoing transfers can share secrethash with incoming ones (e.g. on mediation), so a `transferKey` is also needed, which decouples usage from transfer's internals like `secrethash`

## Steps to Reproduce
1. Enable transfers receiving after #1494 
2. Perform a transfer from another dApp account

## Expected Result
- Transfer is shown as a received transfer on history

## Actual Result
- No received transfer show up

## Additional Infos (Optional) 
Current master

### PR DESCRIPTION
**Pull request by andrevmatos**
Fixes #1503 

**Short description**
Exposes received transfers through `transfers$` observable, define `RaidenTransfer.key` as a unique string key, to be used instead of `secrethash`.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Try repro at linked issue
2. See it works for received transfers:
image

### CODE REVIEW

**Comment by andrevmatos** [comment]
No need for dApp changes changelog, since the issues there didn't affect users since receiving isn't enabled yet.

File: raiden-ts/src/transfers/utils.ts [hunk 1]
```diff
@@ -59,12 +59,50 @@ export function makeMessageId(): UInt<8> {
...
+  return transfer.recipient === state.partner ? Direction.SENT : Direction.RECEIVED;
+}
+
+/**
+ * Get a unique key for a tranfer state or TransferId
+ *
+ * @param state - transfer to get key from, or TransferId
+ * @returns string containing a unique key for transfer
+ */
+export function transferKey(
```
Comment (kelsos) [inline raiden-ts/src/transfers/utils.ts:80]: Just out of curiocity what was the problem that this key solves?

File: raiden-ts/src/utils/rx.ts [hunk 2]
```diff
@@ -55,3 +56,33 @@ export function pluckDistinct<T, R>(...properties: string[]): OperatorFunction<T
...
 }
+
+/**
+ * Creates an operator to output changed values unique by key ([key, value] tuples)
+ * It's equivalent to (from(Object.entries) + distinct), but uses key to prevent memory leak
+ *
+ * @param compareFn - Function to compare equality between two values, default to === (reference)
+ * @returns Operator to map from a record to changed values (all on first)
+ */
+export function distinctRecordValues<R>(
```
Comment (kelsos) [inline raiden-ts/src/utils/rx.ts:67]: :+1:

File: raiden-ts/src/transfers/utils.ts (hunk 1 above)
Comment (andrevmatos) [reply raiden-ts/src/transfers/utils.ts:80]: Same as `channelKey`, hardcoding `secrethash` didn't account for duplications, in transfer's case, incoming and outgoing transfers could have the same secrethash (i.e. mediated transfers), and also secrethash only as a key didn't tell if it was an incoming our outgoing transfer, which was done at a time we only had outgoing transfers.
This _standardizes_ the "uniqueness" of key through this function, and if needed, we can update it in the future, to include other parameters for transfer uniqueness.

**Comment by kelsos** [comment]
Like we discussed codewise looks good :) I still need to check it locally but it seems that everything started misbehaving locally :'(
