### PR TITLE
Fixes token amount display on various screens

### LINKED ISSUE #483: Token screen showing a small token amount looks broken
## Steps to Reproduce
1. Connect to the dApp
2. Select a token
3. Connect to a hub with a very small token amount (`0.0000000000000001`)
4. Go to the "Transfer" screen

## Expected Result
- The following notation is shown: <0.000001
- Tooltip shows full amount
- Rounded at the last digit (≈0.000001)
- 6 digits
- If the amount is bigger (≈0.032335 - if it is not precise - digits afterward)
- For every number

## Actual Result
- Looks broken

    grafik

## Additional Infos (Optional) 
```
Google Chrome | 77.0.3865.120 (Offizieller Build) (64-Bit) (cohort: Stable)
Überarbeitung | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
Betriebssystem | Windows 10 OS Version 1903 (Build 18362.295)
JavaScript | V8 7.7.299.13
```

### PR DESCRIPTION
**Pull request by kelsos**
Closes #483
Modifications on the filters also fix the issue #546

### CODE REVIEW

File: raiden-dapp/src/components/FindRoutes.vue [hunk 1]
```diff
@@ -47,6 +48,7 @@ export default class FindRoutes extends Vue {
   routes!: Route[];
   @Prop({ required: true })
   pfsUrl!: string;
+  selected: Route[] = [];
```
Comment (kelsos) [inline raiden-dapp/src/components/FindRoutes.vue]: This was accidentally removed in the previous PR but it was throwing console errors so I reintroduced it.
