### PR TITLE
sdk: emit logs upon confirmation from fromEthersEvent

### LINKED ISSUE #1936: sdk: contracts events payload values can change in case of reorgs
Our events confirmation logic assumes (mistakenly) that events payload data would remain unchanged in case of reorgs. It expected that reorgs could at most remove the transaction, not mine it with completely different values. Unfortunately, that's the case. Specially with the `channelId` value, this can mess with the events monitoring logic.
This is quite critical, and breaks important assumptions which we made for a few places in the architecture which deal with contracts events and results, but it's mostly only triggerable in stress conditions such as SP's BF6 scenario.

## Steps to Reproduce
1. Run a scenario on SP where several nodes open channels on the same network concurrently (e.g. BF6)
2. If a reorg happen, the confirmed tx can have the same txHash of the first emit, but with different channelId, and deposit will fail and state will be inconsistent.

## Expected Result
- Confirmation logic and events monitoring can cope with reorgs

## Actual Result
- Undefined behavior, inconsistent state

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

### PR DESCRIPTION
**Pull request by andrevmatos**
Fixes #1936 

**Short description**
The problem with our previous confirmation logic was that it only took into account the `txHash` and at most updated a reorged `txBlock`: any pending action payload which depended on values which could change on reorgs (main example is `channel_identifier`, which currently depends strictly on tx order, since it's a nonce number) would get out-of-date and both the unconfirmed and its confirmed reemission would be inconsistent with the blockchain. This was actually witnessed upon stress testing on BF6 scenario on SP, which opens several channels on different clients simultaneously, and a reorg changed the order of the `openChannel` transactions on block and made a totally inconsistent state.

The fix keeps the previous `confirmationEpic`, but which should be used only for ConfirmableActions which have values/payloads which don't depend on order or reorgs of blocks/events on-chain. But now, the main way to confirm a log/event/action is through the same `fromEthersEvent` + `map(logToContractEvent)` utilities, which knows how to re-decode reorged events
- `fromEthersEvent` will watch double the range as before (`2 * confirmationBlocks`)
  - the higher half is for unconfirmed logs/events, as before, and the lower half is dedicated for confirmed logs;
  - unconfirmed logs can be emitted multiple times, in order to update their representation on `pendingTxs` state
  - confirmed actions are emitted as confirmed only once, and may replace the values with the confirmed counterparts; the `afterLogBlock` cleanup only takes place on this 'confirmed' part, to allow unconfirmed actions to be re-fetched
  - it can be used to query from a specific block in the past, taking the role previously with `getEventsStream`, in a sorted and standardized way
- `pendingTxs` reducer now deduplicate ConfirmableActions per action type and `txHash`, ensuring re-emitted unconfirmed actions are updated on state, which may make any depending unconfirmed action also be updated (e.g. deposits over unconfirmed channel)
- `makeDeposit$` function now needs to wait upon `openChannel` tx is confirmed, since it requires the `channelId` which only "stabilizes" after confirmation; `approve` side can still be done in parallel

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Check bug doesn't happen
2. Possible only once we can run BF6 scenario

### CODE REVIEW

File: raiden-ts/src/channels/reducer.ts [hunk 1]
```diff
@@ -34,19 +34,24 @@ const tokens = createReducer(initialState.tokens).handle(
...
   state = initialState.pendingTxs,
   action: RaidenAction,
 ): RaidenState['pendingTxs'] => {
   // filter out non-ConfirmableActions's
   if (!ConfirmableAction.is(action)) return state;
-  // if confirmed==undefined, add action to state
-  else if (action.payload.confirmed === undefined) return [...state, action];
+  // if confirmed==undefined, deduplicate and add action to state
+  else if (action.payload.confirmed === undefined)
+    return [...withoutAction(state, action), action];
```
Comment (weilbith) [inline raiden-ts/src/channels/reducer.ts:51]: Nitpick: this function is **doing** something. So I would use a verb for it like `removeAction()`. The first time I read this (during the meeting) I didn't understood what this should mean. So I actually had to read the function itself to understand the idea. Now it makes sense. Anyways I think this could be improved. There is enough logic you need to understand. Little supporting hints like this are appreciated.

Comment (christianbrb) [reply raiden-ts/src/channels/reducer.ts:51]: @weilbith This reminds of one of the most important books about software programming I have ever read (Code Complete by Steve McConnell - Chapter: Good Routine Names: https://flylib.com/books/en/2.823.1.63/1/).

**Comment by christianbrb** [comment]
@andrevmatos Great PR description and process :) 👍

File: raiden-ts/src/channels/reducer.ts (hunk 1 above)
Comment (andrevmatos) [reply raiden-ts/src/channels/reducer.ts]: Done
