### PR TITLE
Fixed alignment of error messages for address/amount input

### LINKED ISSUE #1085: Nitpick: Visual space between the two lines between the token input field
## Steps to Reproduce
1. Go the "Transfer Screen"
2. Click on "Deposit"
3. Enter an amount larger than your token balance

## Expected Result
- Visual space between the two lines

## Actual Result
- Nearly no space between the two lines below the token input field

grafik

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

### PR DESCRIPTION
**Pull request by nephix**
Resolves #1085

Didn't add change log entry because changes were really small

### CODE REVIEW

File: raiden-dapp/src/components/ErrorMessage.vue [hunk 1]
```diff
@@ -1,20 +1,22 @@
...
-    </label>
-    <p>{{ problem }}</p>
-    <label class="error-message__label">
-      {{ $t('error-message.solution') }}
-    </label>
-    <ol v-if="Array.isArray(solution)">
-      <li v-for="step in solution" :key="step">{{ step }}</li>
-    </ol>
-    <p v-else>{{ solution }}</p>
+    <v-col cols="12">
```
Comment (nephix) [inline raiden-dapp/src/components/ErrorMessage.vue]: Unrelated fix, but the `v-col` was missing here inside the `v-row` sometimes causing weird looking behavior on mobile
