### PR TITLE
Fixes width of transfer inputs on mobile devices

### LINKED ISSUE #1243: Transfer screen inputs are full width on mobile
## Steps to Reproduce
1. Serve dapp
2. Connect

## Expected Result
- On mobile, the address and amount inputs are `col-10-sm` wide

## Actual Result
- The inputs are full width

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1243

### CODE REVIEW

File: raiden-dapp/src/views/Transfer.vue [hunk 1]
```diff
@@ -63,7 +63,7 @@
       @submit.prevent="navigateToTransferSteps(target, amount)"
     >
       <v-row justify="center" align="center" class="transfer__recipient">
-        <v-col cols="12" sm="10">
```
Comment (nephix) [inline raiden-dapp/src/views/Transfer.vue]: I think it worked before with `cols="12" sm="10"` as well, but I accidentally moved the `v-form` next to a row which seems to cause this issue. Looks like vuetify only wants v-rows to have v-row siblings

Comment (kelsos) [reply raiden-dapp/src/views/Transfer.vue]: Yes, it could possibly be it. I didn't spend more time looking into it as the change seems to have the required result :)

Comment (nephix) [reply raiden-dapp/src/views/Transfer.vue]: Yes no big deal =)
