### PR TITLE
dapp: fix empty logs in production mode

### LINKED ISSUE #2754: Download Log downloads empty log file with zero size
## Steps to Reproduce
Start raiden dapp on the ~~`next`~~  `next_address_metadata` branch
1. Click on the identicon
2. Click of `Download logs`

## Expected Result
- A file with the logs would be downloaded 

## Actual Result
- Empty file is downloaded

### PR DESCRIPTION
**Pull request by weilbith**
Fixes #2754

**Short description**
See the issue and the commit message for details of the bugs origin and solution.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Build the dApp for production and serve it locally
2. Connect to the dApp and download the logs
3. Make sure the downloaded file is not empty

### CODE REVIEW

File: raiden-dapp/src/utils/logstore.ts [hunk 1]
```diff
@@ -98,14 +99,19 @@ export async function setupLogStore(additionalLoggers: string[] = ['matrix']): P
...
+      loggerName: string | symbol,
+    ): LoggingMethod {
       const rawMethod = origFactory(methodName, level, loggerName);
       const name = loggerName.toString();
       setDbForLogger(name);
 
       // eslint-disable-next-line @typescript-eslint/no-explicit-any
       return (...message: any[]): void => {
-        rawMethod(...message);
+        rawMethod.apply({}, [...message]);
```
Comment (palango) [inline raiden-dapp/src/utils/logstore.ts:114]: Could this have any unintended consequences?

File: raiden-ts/src/logger.ts [hunk 2]
```diff
@@ -7,9 +7,9 @@ Object.defineProperty(logging, 'methodFactory', {
   get() {
     return curMethodFactory;
   },
-  set(func: typeof curMethodFactory) {
+  set(func: typeof curMethodFactory & { allow_overwrite?: boolean }) {
     /* prevent anyone else but us (e.g. matrix) from overwriting methodFactory  */
-    if (!func.name?.startsWith('raiden')) return;
+    if (!func.allow_overwrite) return;
```
Comment (andrevmatos) [inline raiden-ts/src/logger.ts:12]: Please, also add this property to the `cli`'s logger, or it won't work there.

File: raiden-dapp/src/utils/logstore.ts (hunk 1 above)
Comment (andrevmatos) [inline raiden-dapp/src/utils/logstore.ts:114]: Nitpick: 
```suggestion
        rawMethod.apply({}, message);
```

File: raiden-ts/src/logger.ts (hunk 2 above)
Comment (weilbith) [reply raiden-ts/src/logger.ts:12]: Ah damn. I checked the SDK for any modification, but forgot the CLI. Thanks for reminding me!

File: raiden-dapp/src/utils/logstore.ts (hunk 1 above)
Comment (weilbith) [reply raiden-dapp/src/utils/logstore.ts:114]: To be honest, I'm not 100% sure. From reading the libraries code around [this location](https://github.com/pimterry/loglevel/blob/342f103eed48f29db854533d2cbfe254690f9113/lib/loglevel.js#L84) it looks like this should be fine. Practical tests seem to have proven that it works. Combining these two I'm optimistic its fine. But maybe you see something?

Comment (weilbith) [reply raiden-dapp/src/utils/logstore.ts:114]: I also don't found any further details in the issues.

Comment (weilbith) [reply raiden-dapp/src/utils/logstore.ts:114]: This is intended. Else I get an error that instead of one or two arguments I provide one or more.

Comment (weilbith) [reply raiden-dapp/src/utils/logstore.ts:114]: I just see that in the CLI we put in our own this. So maybe we just do that here as well.

Comment (andrevmatos) [reply raiden-dapp/src/utils/logstore.ts:114]: This would be just an optimization, `[...message]` is just creating a shallow copy of the arguments array. Shallow copies are cheap, the nitpick was just to avoid it. The error can be fixed if you type the params as `(...message: [any, ...any[]])` or something like that, but don't mind.

Comment (weilbith) [reply raiden-dapp/src/utils/logstore.ts:114]: Alright, I have a better solution. 👍🏾

File: raiden-ts/src/logger.ts (hunk 2 above)
Comment (weilbith) [reply raiden-ts/src/logger.ts:12]: ✔️

File: raiden-dapp/src/utils/logstore.ts (hunk 1 above)
Comment (weilbith) [reply raiden-dapp/src/utils/logstore.ts]: I have chosen to go for the `call` variant as some code above changed and also uses the `call` variant already in the CLI.
Done. ✔️

Comment (palango) [reply raiden-dapp/src/utils/logstore.ts]: Together with link I think this is fine.

File: raiden-ts/src/logger.ts [hunk 3]
```diff
@@ -7,9 +7,9 @@ Object.defineProperty(logging, 'methodFactory', {
   get() {
     return curMethodFactory;
   },
-  set(func: typeof curMethodFactory) {
+  set(func: typeof curMethodFactory & { allow_overwrite?: boolean }) {
```
Comment (andrevmatos) [inline raiden-ts/src/logger.ts:10]: Nitpick, can we name this var in camelCase instead of snake_case? To keep consistency with the our naming convention

Comment (weilbith) [reply raiden-ts/src/logger.ts:10]: Ofc. Sorry, in my free time I currently use languages where snake case is the standard. 🙈

Comment (weilbith) [reply raiden-ts/src/logger.ts]: ✔️

**Comment by weilbith** [comment]
Okay I tested it again with everything freshly build and served on a new port I never used before locally. New account works fine, logs look good. Would be cool if someone could verify that (@palango ?)

**Review by andrevmatos — APPROVED** [review]
lgtm, nice finding, thanks

**Comment by palango** [comment]
Sure, I can test again.

**Comment by palango** [comment]
@weilbith Yes, logs work with this PR applied. Great fix!

**Comment by weilbith** [comment]
So I still need to fix the broken tests now.

**Comment by weilbith** [comment]
Alright it was just a CI issue with CircleCI their infrastructure issues. I now just add a final CHANGELOG entry and then merge it.
