### PR TITLE
Shut down if database is deleted

### LINKED ISSUE #2360: dApp does not connect after deleting all local data
## Steps to Reproduce
1. Open a channel on https://lightclient.raiden.network/
2. Make transfers
3. Delete Cache, Cookies, IndexedDB, LocalStorage and Session Storage
4. Go to https://lightclient.raiden.network/
5. Accept the disclaimer
6. Generate Raiden Account

## Expected Result
- I am on the transfer screen and see my full deposit as capacity

## Actual Result
- The spinner on the connect button is spinning

[raiden_2020-11-13T09 00 37.777Z.log](https://github.com/raiden-network/light-client/files/5535801/raiden_2020-11-13T09.00.37.777Z.log)

This web console error is not stored in the logs:

grafik

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

### PR DESCRIPTION
**Pull request by andrevmatos**
Fixes #2360 

**Short description**
Improved by https://github.com/pouchdb/pouchdb/pull/8230 , but should already be mergeable before that.

So far, `persister` errors were just logged and ignored. This PR handles it, and properly shuts down the SDK if they happen, since they aren't expected. Also, it checks properly that the database version didn't change and errors if so, which is one indicator that the database got deleted. The linked upstream PR should also throw on the async `db.info()` call, ensuring the state machine doesn't proceed if state got cleared.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

0. Install linked PR as dependency
1. Run a new dApp, see its state be created
2. While dApp is connected, clear state
3. See SDK shutdown on next state change attempt

### CODE REVIEW

**Comment by andrevmatos** [comment]
Upstream PR merged, may take a while for a release though

File: raiden-ts/src/epics.ts [hunk 1]
```diff
@@ -167,8 +168,9 @@ export function raidenRootEpic(
     // wire deps.latest$ when observableFactory below gets subscribed, and tears down on complete
     () => getLatest$(limitedAction$, limitedState$, deps).subscribe(deps.latest$),
     () =>
-      // like combineEpics, but completes action$, state$ & output$ when a raidenShutdown goes through
-      from(Object.values(RaidenEpics)).pipe(
```
Comment (palango) [inline raiden-ts/src/epics.ts:171]: Will the epics be restarted? Or will the user need to reload?

**Review by palango — APPROVED** [review]
lgtm

File: raiden-ts/src/epics.ts (hunk 1 above)
Comment (andrevmatos) [reply raiden-ts/src/epics.ts:171]: This is a fatal, unexpected, non-recoverable error. It'll shutdown for good, and the user needs to reload when this happens.
