### PR TITLE
Fix nonce mismatch caused by rooms waiting overhead upon sending messages

### LINKED ISSUE #2229: Nonce mismatches for LockedTransfer message
I am still getting Nonce mismatches when using the dApp to do direct transfers with a Raiden python node.
Corresponding Python Raiden node log entry:

``` json
{
  "node": "0x11faFfcc7Aa31d731a8Cf6e998216731ed78D7AF",
  "raiden_events": [
    {
      "reason": "Invalid LockedTransfer message. Nonce did not change sequentially, expected: 3 got: 1.",
      "payment_identifier": "3893759327999191202",
      "_type": "raiden.transfer.events.EventInvalidReceivedLockedTransfer"
    },
    {
      "secrethash": "0xd50a1a8df7508f769964be2a384b8bb0cb39f9e7b0fcb04c3dd272ee7397953c",
      "reason": "Invalid LockedTransfer message. Nonce did not change sequentially, expected: 3 got: 1.",
      "identifier": "3893759327999191202",
      "_type": "raiden.transfer.mediated_transfer.events.EventUnlockClaimFailed"
    }
  ],
  "event": "Raiden events",
  "logger": "raiden.raiden_service",
  "level": "debug",
  "greenlet_name": "GMatrixClient.message_worker user_id:@0x11faffcc7aa31d731a8cf6e998216731ed78d7af:transport.demo001.env.raiden.network",
  "timestamp": "2020-10-12 08:01:00.921479"
}

```

## Steps to Reproduce
1. Used the `lightclient.raiden.network/staging` across several versions, clicking the refresh button on version updates
2. Due to previous nonce mismatches closed a channel with transaction partner.
3. Opened a new funded channel with transaction partner node (Raiden Python 1.1.1) on Goerli.
4. Did one direct transfer that succeeded, closed the dApp immediately
5. Tried another direct transfer, that gets retried on the dApp side and remains pending, while messages are being ignored on the transaction partner side due to nonce mismatches.

No version refreshes were conducted on the dApp side between steps 3. and 5.

## Expected Result
- Transfers should succeed, state should be persisted immediately in the dApp, even though the dApp is closed after successful transfers.

## Actual Result
- Pending transfer on sender side / rejected message on receiver side due to lower nonce on a transfer after closing and re-opening the dApp.

## Additional Infos (Optional) 
```
- Google Chrome (Version 85.0.4183.121)
- MacOS 10.15.7
```

[raiden_0x68aD5215b1791E5608bcf825477af114B799022D_2020-10-12T08_02_01.869Z.log](https://github.com/raiden-network/light-client/files/5363808/raiden_0x68aD5215b1791E5608bcf825477af114B799022D_2020-10-12T08_02_01.869Z.log)

[raiden-debug_2020-10-12T07:44:28.131240.log](https://github.com/raiden-network/light-client/files/5363816/raiden-debug_2020-10-12T07.44.28.131240.log)

### PR DESCRIPTION
**Pull request by andrevmatos**
Fixes #2229

**Short description**
This was a little bit hard to debug, but it seems some overhead upon explicitly queueing messages and waiting for peer to join the room with us caused some overhead which prevented the persistence callbacks from firing at proper time.
This PR was tested using BF6, and as the presence bug was kicking in, it also includes a workaround for it, by explicitly requesting peer's presence upon presence events, instead of relying on event's payload, which can be wrong.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Test bug doesn't occur
2. High-load scenarios pass

### CODE REVIEW

**Comment by andrevmatos** [comment]
@ezdac Please, test if this fixes your bug. I'd suggest:
- Ensure dependencies are up to date, with `pnpm install --prefer-frozen-lockfile` on repo's root
- Build SDK: `pnpm run build --filter raiden-ts`
- Serve dApp: `pnpm run serve --filter raiden-dapp`
- Use a fresh account, or close+settle channels and clear IndexedDB before reloading dApp
- Test

File: raiden-ts/src/transport/epics/presence.ts [hunk 1]
```diff
@@ -209,28 +209,32 @@ export function matrixPresenceUpdateEpic(
...
-        // first filter can't tell typescript this property will always be set!
-        const userId = user.userId,
-          presence = user.presence!,
-          available = AVAILABLE.includes(presence);
-
-        // always fetch profile info, to get up-to-date displayname & avatar_url
-        return defer(() => matrix.getProfileInfo(userId)).pipe(
-          map((profile) => {
+      mergeMap(([{ matrix, user, address }, , { pollingInterval, httpTimeout }]) =>
+        defer(async () =>
```
Comment (palango) [inline raiden-ts/src/transport/epics/presence.ts:213]: I guess you should use `retryAsync$` here to handle matrix rate-limit erros

Comment (andrevmatos) [reply raiden-ts/src/transport/epics/presence.ts:213]: It is handled, but using `retryWaitWhile` a little down this observable chain

File: raiden-ts/src/transport/epics/helpers.ts [hunk 2]
```diff
@@ -145,12 +150,12 @@ export function waitMemberAndSend$<C extends { msgtype: string; body: string }>(
       // up to RETRY_COUNT times; if it continues to error, throws down
       err$.pipe(
         withLatestFrom(config$),
-        mergeMap(([err, { pollingInterval }], i) => {
-          if (i < RETRY_COUNT - 1) {
-            log.warn(`messageSend error, retrying ${i + 1}/${RETRY_COUNT}`, err);
+        mergeMap(([err, { pollingInterval }], count) => {
+          // always retry rate-limit errors
+          if (count < RETRY_COUNT - 1 || err?.httpStatus === 429) {
+            log.warn(`messageSend error, retrying ${count + 1}/${RETRY_COUNT}`, err);
```
Comment (palango) [inline raiden-ts/src/transport/epics/helpers.ts:156]: Here you don't use `retryWaitWhile` because you want to log something, right?

File: raiden-ts/src/transport/epics/messages.ts [hunk 3]
```diff
@@ -59,37 +58,29 @@ export function matrixMessageSendEpic(
...
+          : encodeJsonMessage(action.payload.message);
+      const content = { body, msgtype: 'm.text' };
+      // wait for address to be monitored, online & have joined a non-global room with us
+      return waitMemberAndSend$(
+        action.meta.address,
+        matrix,
+        'm.room.message',
+        content,
+        { log, latest$, config$ },
+        true, // alowRtc
```
Comment (palango) [inline raiden-ts/src/transport/epics/messages.ts:75]: s/alowRtc/allowRtc

File: raiden-ts/src/transport/epics/helpers.ts (hunk 2 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/helpers.ts:156]: Yes, exactly. We could look into adding some message to be logged to `retryWaitWhile`/`retryAsync$`, but since this isn't that common, I didn't do it yet on this PR

File: raiden-ts/src/transport/epics/messages.ts [hunk 4]
```diff
@@ -59,37 +58,29 @@ export function matrixMessageSendEpic(
     filter(isActionOf(messageSend.request)),
     // this mergeMap is like withLatestFrom, but waits until matrix$ emits its only value
     mergeMap((action) => matrix$.pipe(map((matrix) => ({ action, matrix })))),
-    groupBy(({ action }) => action.meta.address),
     // merge all inner/grouped observables, so different user's "queues" can be parallel
```
Comment (palango) [inline raiden-ts/src/transport/epics/messages.ts:61]: This removes per-user queuing. Should we create an issue to bring it back?

File: raiden-ts/src/transport/epics/presence.ts (hunk 1 above)
Comment (palango) [reply raiden-ts/src/transport/epics/presence.ts:213]: Missed that one, thanks!

File: raiden-ts/src/transport/epics/messages.ts [hunk 5]
```diff
@@ -215,21 +206,24 @@ export function matrixMessageReceivedEpic(
         // take up to an arbitrary timeout to presence status for the sender
         // AND the room in which this message was sent to be in sender's address room queue
         takeUntil(timer(httpTimeout)),
-        mergeMap(function* ({ presences }) {
+        mergeMap(({ presences }) => {
```
Comment (palango) [inline raiden-ts/src/transport/epics/messages.ts:209]: Nice, that change makes it easier to read.

File: raiden-ts/src/transport/epics/messages.ts (hunk 4 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/messages.ts:61]: I don't think so. Queueing may be useful, but here, it was just causing overhead. Since `waitMemberAndSend$` will wait for the perfect set of conditions to align before attempting sending, and reactively waiting is cheaper than the queue and creates an _implicit_ queue (for the messages waiting to be sent), we don't need the explicit queue here anymore.

File: raiden-ts/src/transport/epics/webrtc.ts [hunk 6]
```diff
@@ -436,12 +452,11 @@ function handlePresenceChange$(
       // if peer goes offline in Matrix, reset dataChannel & unsubscribe defer to close dataChannel
       if (!action.payload.available) return of(rtcChannel(undefined, action.meta));
 
-      const deps = { log, latest$, config$ };
       const callId = [address, action.meta.address]
         .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))
         .join('|');
       const isCaller = callId.startsWith(address);
-      const timeoutGen = exponentialBackoff(config.pollingInterval, 2 * config.httpTimeout);
```
Comment (palango) [inline raiden-ts/src/transport/epics/webrtc.ts:444]: Can you add a comment on why a lower multiplier is used here?

**Review by palango — APPROVED** [review]
Looks good from my side. Left some comments where had some remarks.

I guess codeclimate is right here in that some of those are massive and we need to try to make them smaller!

**Review by weilbith — COMMENTED** [review]
Just some comments. I need to get more into the SDK again. It is so complex to read. :see_no_evil:

File: raiden-ts/src/transport/epics/messages.ts (hunk 4 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/messages.ts:72]: Each element next'ed on this observable will end up and stop at this `waitMemberAndSend$`. This function returns an observable, which is also immediately subscribed, and which will only emit once the _set of conditions_ met (e.g. partner is online and has joined a room with us). Then, in the order these observables were created, they're resolved by the event which fulfilled them (e.g. the membership event when partner joined the room), and therefore this makes an implicit queue, where the async callbacks are called in order, but they're resolved **parallelly**, but which isn't a problem since we want all messages sent anyway.

File: raiden-ts/src/transport/epics/presence.ts [hunk 7]
```diff
@@ -209,28 +209,32 @@ export function matrixPresenceUpdateEpic(
...
             // ecrecover address, validating displayName is the signature of the userId
-            const recovered = verifyMessage(userId, profile.displayname) as Address | undefined;
+            const recovered = verifyMessage(user.userId, profile.displayname) as
+              | Address
+              | undefined;
             assert(
               recovered === address,
               `invalid displayname signature: ${recovered} !== ${address}`,
             );
+            const available = AVAILABLE.includes(presence);
```
[the remark this answers is not in the document]
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/presence.ts:228]: We can name it in a future PR, but AVAILABLE here is an array containing the presences which are considered available.

File: raiden-ts/src/transport/epics/helpers.ts [hunk 8]
```diff
@@ -70,25 +70,24 @@ function waitMember$(
...
-    ),
-    pluck(1),
-    take(1),
+    switchMap(([presence, room]) => {
+      if (!presence.payload.available) return EMPTY;
+      const member = room.getMember(presence.payload.userId);
+      if (member?.membership === 'join') return of(room.roomId);
+      return fromEvent<[MatrixEvent, RoomMember]>(matrix, 'RoomMember.membership').pipe(
+        filter(([, { roomId, membership }]) => roomId === room.roomId && membership === 'join'),
+        pluck(1, 'roomId'),
```
[the remark this answers is not in the document]
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/helpers.ts:88]: Yes, exactly. As soon as an event pass the filter, it'll output the `roomId`.

File: raiden-ts/src/transport/epics/webrtc.ts [hunk 9]
```diff
@@ -163,63 +166,76 @@ function handleCandidates$(
...
-    // when receiving candidates from peer, add it locally
-    matrixWebrtcEvents$(matrix, RtcEventType.candidates, peerId).pipe(
-      tap((e) => log.debug('RTC: received candidates', callId, e.candidates)),
-      mergeMap((event) => from((event.candidates ?? []) as RTCIceCandidateInit[])),
-      mergeMap((candidate) =>
-        defer(() => connection.addIceCandidate(candidate)).pipe(
-          catchError((err) => {
-            log.error('RTC: error setting candidate, ignoring', err);
-            return EMPTY;
+  const { log, config$ } = deps;
```
[the remark this answers is not in the document]
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/webrtc.ts:173]: Whatever keeps codeclimate happy xD

File: raiden-ts/src/transport/epics/webrtc.ts [hunk 10]
```diff
@@ -163,63 +166,76 @@ function handleCandidates$(
   matrix: MatrixClient,
   start$: Observable<null>,
   { callId, peerId, peerAddress }: CallInfo,
-  { log, latest$, config$ }: Pick<RaidenEpicDeps, 'log' | 'latest$' | 'config$'>,
+  deps: Pick<RaidenEpicDeps, 'log' | 'latest$' | 'config$'>,
 ) {
-  return merge(
```
[the remark this answers is not in the document]
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/webrtc.ts:168]: It was clearer before, but then the last commit had to move code around to make codeclimate happy, and this messed up the patches, sorry about it. It's just extracting the big `switchMap` callback to the function, and putting the rest of it back on the epic function, so both ends up with less than 50 LoC.

File: raiden-ts/src/transport/epics/presence.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (weilbith) [reply raiden-ts/src/transport/epics/presence.ts:228]: Ups..

File: raiden-ts/src/transport/epics/webrtc.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (weilbith) [reply raiden-ts/src/transport/epics/webrtc.ts:173]: I feel connected to it. :stuck_out_tongue:
