### PR TITLE
Adjusts the scrollbar scss on Firefox and webkit based browsers

### LINKED ISSUE #482: Remove/hide scrollbar from list
## Steps to Reproduce
1. Connect to the dApp

## Expected Result
- Remove or hide slider when the amout of tokens displayed do not require any scrolling.
- Play around with the CSS properties for various browsers and try to make it blend in with the rest of the dApp design.

## Actual Result
- I see the token list with a slider on the right (see screenshot)

    grafik

## Additional Infos (Optional) 
```

Google Chrome | 77.0.3865.120 (Offizieller Build) (64-Bit) (cohort: Stable)
Überarbeitung | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
Betriebssystem | Windows 10 OS Version 1903 (Build 18362.295)
JavaScript | V8 7.7.299.13


```

### PR DESCRIPTION
**Pull request by kelsos**
Closes #482

### CODE REVIEW

File: raiden-dapp/src/components/TokenOverlay.vue [hunk 1]
```diff
@@ -177,6 +183,11 @@ export default class TokenOverlay extends Mixins(
     }
   }
 
+  .token-list__item-list {
```
Comment (nephix) [inline raiden-dapp/src/components/TokenOverlay.vue]: Could be simplified to
```
.token-list {
  ...
  &__item-list { ... }
}
```
with def. above
