### PR TITLE
Retry contract calls when network problems occur

### LINKED ISSUE #2240: Handle ETH node connection problems gracefully
## Thanks for filing a bug report :-)

During the nightly run the PFS8 scenario failed.

Might be related to https://github.com/raiden-network/raiden/issues/6612

The light client seems to have crashed and returned a 500 error code
```
scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:56049/api/v1/channels. Expected 201: <!DOCTYPE html>
<html lang=\"en\">
<head>
<meta charset=\"utf-8\">
<title>Error</title>
</head>
<body>
<pre>InternalServerError: invalid response - 0
    at Object.internalErrorHandler (/lc/index.js:221624:31)
    at Layer.handle_error (/lc/index.js:47797:5)
    at trim_prefix (/lc/index.js:47371:13)
    at /lc/index.js:47340:7
    at Function.process_params (/lc/index.js:47391:12)
    at next (/lc/index.js:47331:10)
    at Layer.handle_error (/lc/index.js:47793:12)
    at trim_prefix (/lc/index.js:47371:13)
    at /lc/index.js:47340:7
    at Function.process_params (/lc/index.js:47391:12)</pre>
</body>
</html>
```

Logs:
[scenario-player-run_pfs8_mediator_goes_offline_2020-10-13T16:24:55.log.gz](https://github.com/raiden-network/light-client/files/5376971/scenario-player-run_pfs8_mediator_goes_offline_2020-10-13T16.24.55.log.gz)

## Expected Result
- Scenario should pass

### PR DESCRIPTION
**Pull request by palango**
**Thank you for submitting this pull request :)**

Fixes #2240 

**Short description**

Retry contract calls **in epics** when network problems occur. We leave the raiden class for now, some of its functions should be converted to epics as described in #1908.

**Definition of Done**

- [ ] Steps to manually test the change have been documented
- [ ] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.
2.

### CODE REVIEW

File: raiden-ts/src/channels/utils.ts [hunk 1]
```diff
@@ -313,3 +313,14 @@ export function approveIfNeeded$(
...
+
+/**
+ * Predicate to that fiters erros for retrieable network problems. To be used with `retryAsync$`.
+ *
+ * @param error - Error in question
+ * @returns `False`, if there was a retrieable network error.
+ */
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+export function networkErrorRetryPredicate(error: any, {}): boolean {
+  return !error?.includes(`invalid response`);
```
Comment (andrevmatos) [inline raiden-ts/src/channels/utils.ts:325]: Error is most likely an `Error` instance, so you should use something like:
```suggestion
  return !(typeof error?.message === 'string' && error.message.includes(`invalid response`));
```

**Comment by andrevmatos** [comment]
This is good, thank you very much; please, also check `assertTx`'s `tx.wait()`, since this probably is also a source of the error mentioned in the issue.

File: raiden-ts/src/channels/utils.ts [hunk 2]
```diff
@@ -282,6 +288,7 @@ export function approveIfNeeded$(
   tokenContract: HumanStandardToken,
   spender: Address,
   approveError: string = ErrorCodes.RDN_APPROVE_TRANSACTION_FAILED,
+  provider: JsonRpcProvider,
```
Comment (andrevmatos) [inline raiden-ts/src/channels/utils.ts:291]: Suggestion:
```suggestion
  { provider }: Pick<RaidenEpicDeps, 'provider'>,
```
To match `assertTx`'s signature, and make it easier to require other deps if needed in the future.

**Review by andrevmatos — APPROVED** [review]
lgtm. I hope in the future we can refactor most of this to a dedicated `txEpic` or so, an epic/service which centralizes dispatching transactions, but at least the read-only ones may remain.
Thanks

**Review by andrevmatos — APPROVED** [review]
lgtm, good job!
