### PR TITLE
Proper fees dialogs behavior if direct route available, single free PFS or single free route

### LINKED ISSUE #596: Can't use a PFS set in config
## Steps to Reproduce
1. Get the `raiden` SDK instance on browser's dev tool
2. Set a config with `raiden.updateConfig({ pfs: 'https://pfs-goerli-with-fee.services-test.raiden.network' })`
3. Try to perform a transfer

## Expected Result
- Skip PFS selection dialog and call `findRoutes` without specifying a `pfs` if `raiden.config.pfs !== undefined`
- Can fetch routes and transfer using this set PFS

## Actual Result
image

### PR DESCRIPTION
**Pull request by andrevmatos**
Fix #596 

- There's a new method available, `Raiden.directRoute`, similar to `findRoutes`, which can get earlier if a direct route is available
  - This can be used to skip PFS fee & mediation fee dialogs
  - It resolves to `undefined` if no direct route is found; rejects only if validation fails (e.g. token address), not on route not found like `findRoutes`
- `findPFS` will throw only if pfs is disabled in config (`config.pfs=null`), `directRoute` before can skip this error if direct transfer is possible; it uses set `config.pfs`, or fetches from `ServiceRegistry` only if `undefined` (default)
- Should skip PFS fee dialog if `findPFS` finds a single free (price=0) PFS
- Should skip mediation fee dialog if `findRoutes` finds a single free route

So, general dApp workflow should be like:
- call `Raiden.directRoute`
  - if there's a direct route: use it as `paths` for `transfer` in last point directly
  - else (resolves to undefined)
    - call `findPFS`
      - if throws, show error, means no direct route and PFS disabled
      - if returns a single free PFS, auto-confirm (skip) PFS fee dialog
      - else, show dialog and let the user select and confirm payment for a PFS
    - call `findRoutes` with selected `pfs` above
      - if there's a single free route, auto-confirm (skip) mediation fee dialog
      - else, show dialog and let user select and confirm a route and its fee
- call `transfer` with selected `paths`

### CODE REVIEW

**Comment by christianbrb** [comment]
This would fix #408

**Comment by kelsos** [comment]
@andrevmatos I should be done with the dApp part. I did try it by hand also and it seems to work properly. I am not sure if you also want to have a look. 

I would like to re-evaluate what happens if for example you have free pfs and there is no route. Do you go back to the previous `transfer` screen or you go to the select PFS step. But these are mostly UX matters. We can try the scenarios mentioned and then maybe @taleldayekh can help us plan the user flow in these cases better.

File: raiden-dapp/src/services/raiden-service.ts [hunk 1]
```diff
@@ -338,6 +338,15 @@ export default class RaidenService {
     return this.raiden.config.pfs === undefined;
```
Comment (andrevmatos) [inline raiden-dapp/src/services/raiden-service.ts]: I think you may remove the `noPfsSelected` now, you shouldn't need to inspect it, right?

File: raiden-dapp/src/views/TransferSteps.vue [hunk 2]
```diff
@@ -353,6 +378,13 @@ export default class TransferSteps extends Mixins(
             path
           } as Route)
       );
+
+      const [route] = this.routes;
+
+      if (route && route.fee.isZero()) {
+        this.selectedRoute = route;
+        this.transfer();
```
Comment (nephix) [inline raiden-dapp/src/views/TransferSteps.vue]: Maybe go to step 3 first and let the user confirm the transfer. Otherwise from UX he would see the 3 steps at the top and then move directly from 2nd step to the transfer screen. Very minor

File: raiden-dapp/tests/unit/views/transfer-steps.spec.ts [hunk 3]
```diff
@@ -240,4 +247,47 @@ describe('TransferSteps.vue', () => {
     expect(transferDone).toBeCalledTimes(0);
     expect(wrapper.vm.$data.error).toEqual('failure');
   });
+
+  test('skip to transfer if a direct route is available', async () => {
```
Comment (nephix) [inline raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: `'Should...'`

File: raiden-dapp/tests/unit/views/transfer-steps.spec.ts [hunk 4]
```diff
@@ -240,4 +247,47 @@ describe('TransferSteps.vue', () => {
...
+    expect.assertions(2);
+    $raiden.directRoute.mockResolvedValueOnce([freeRoute] as RaidenPaths);
+    $raiden.transfer.mockResolvedValueOnce(undefined);
+    const wrapper = createWrapper({});
+    await flushPromises();
+    expect(wrapper.vm.$data.step).toBe(1);
+    expect($raiden.transfer).toHaveBeenCalledTimes(1);
+  });
+
+  test('skip to transfer if a free route is available', async () => {
```
Comment (nephix) [inline raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: `'Should...'`

File: raiden-dapp/src/services/raiden-service.ts (hunk 1 above)
Comment (kelsos) [reply raiden-dapp/src/services/raiden-service.ts]: I am on it :) I will add an extra commit removing it

File: raiden-dapp/tests/unit/views/transfer-steps.spec.ts [hunk 5]
```diff
@@ -240,4 +247,47 @@ describe('TransferSteps.vue', () => {
...
+    });
+
+    await flushPromises();
+    wrapper.find('.action-button__button').trigger('click');
+    await flushPromises();
+    expect(wrapper.vm.$data.step).toBe(1);
+    expect($raiden.transfer).toHaveBeenCalledTimes(1);
+  });
+
+  test('skip pfs selection if free pfs is found', async () => {
```
Comment (nephix) [inline raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: `'Should...'`

File: raiden-ts/src/path/actions.ts [hunk 6]
```diff
@@ -14,7 +14,10 @@ type ServiceId = {
   serviceAddress: Address;
 };
 
-export const pathFind = createStandardAction('pathFind')<{ paths?: Paths; pfs?: PFS }, PathId>();
+export const pathFind = createStandardAction('pathFind')<
```
Comment (nephix) [inline raiden-ts/src/path/actions.ts]: `typesafe-actions` v4 seem to have a new way of creating standard actions. Do you see any benefit of migrating to the new style when we create new actions or touch old ones?

File: raiden-ts/tests/e2e/raiden.spec.ts [hunk 7]
```diff
@@ -794,17 +794,37 @@ describe('Raiden', () => {
   });
 
   describe('findPFS', () => {
-    test('fail config.pfs not in auto mode', async () => {
-      expect.assertions(2);
+    test('fail config.pfs disabled', async () => {
```
Comment (nephix) [inline raiden-ts/tests/e2e/raiden.spec.ts]: Any merit to applying `'Should...'` also to the SDK?

File: raiden-dapp/src/views/TransferSteps.vue (hunk 2 above)
Comment (kelsos) [reply raiden-dapp/src/views/TransferSteps.vue]: We already discussed with @taleldayekh that this flow can get improved. The plan is to evaluate all the possible scenarios and figure out the proper flow.

File: raiden-dapp/tests/unit/views/transfer-steps.spec.ts (hunk 3 above)
Comment (kelsos) [reply raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: When it comes to jasmine's `it` `Should` sounds like the natural next step. Is that a common convention for jest test naming too?

Comment (nephix) [reply raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: That's what we have always used in the past, I guess it has not so much to do with jest or jasmine but it's one of many naming conventions. Maybe we can decide on one in the test refactor ticket and just leave them here as they are? Here are more "patterns": https://dzone.com/articles/7-popular-unit-test-naming

PS: `test('Should fail when x y z')` also sounds pretty natural :)

Comment (kelsos) [reply raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: @andrevmatos it would be nice to have a consistent naming strategy in the tests accross the SDK in general it would be nice to also have your input here.

Comment (andrevmatos) [reply raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: On the SDK, `test` doesn't use `should`, I usually just name the test in a descriptive way, like `test('fail when amount is negative', () => ...`

Comment (kelsos) [reply raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: I don't mind doing this way either and since I am touching all the tests anyway it would not be much @nephix are you ok with changing the tests in the dapp to follow the same scheme?

File: raiden-ts/src/path/actions.ts (hunk 6 above)
Comment (andrevmatos) [reply raiden-ts/src/path/actions.ts]: Hmm, which new way? From [what I can see](https://github.com/piotrwitek/typesafe-actions#2-fsa-compliant-actions), this is still how it's done. Anyway,  I'd say we shouldn't touch this now, and consider #591 when we need to migrate to anything else (probably a custom implementation based on typesafe-actions and io-ts by then)

File: raiden-dapp/tests/unit/views/transfer-steps.spec.ts (hunk 3 above)
Comment (nephix) [reply raiden-dapp/tests/unit/views/transfer-steps.spec.ts]: Sure sounds good!

File: raiden-ts/src/path/actions.ts (hunk 6 above)
Comment (nephix) [reply raiden-ts/src/path/actions.ts]: We had a dependency PR https://github.com/raiden-network/light-client/pull/474#issuecomment-549709382 that tried to bump the version to 5.x which deprecates the way actions are created in 4.x (like we do currently). The "old" way still works if we use `createStandardAction` from `deprecated`

Comment (andrevmatos) [reply raiden-ts/src/path/actions.ts]: Hmm, right.. didn't see the changes in new release, we may move forward then to the serializable approach. Thank you for pointing this out.
