### PR TITLE
Send messages preemptively and use RTC channel as presence complement

### LINKED ISSUE #2303: BF1 gets No route between nodes found
## Thanks for filing a bug report :-)
Failure dates 31st Oct and 01, 02 November 2020
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
`HTTP status code “409” while fetching http://127.0.0.1:39243/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x66E7d2dC38f884024Ba8B8F95D9d7a4E8a8566ff. Expected 2..: {“message”:”No route between nodes found.”,”details”:””}`

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

### LINKED ISSUE #2352: SecretRequest never arrives at py-raiden node
Not sure wether this is light-client related, py-raiden or protocol related.
This seemed to work before the latest update at `lightclient.raiden.network`

## Steps to Reproduce
1. Open funded direct channel from py-raiden-sender node (on goerli, demo env) with current `lightclient.raiden.network` node
2. Send transfer to lightclient node 
```
partner='0x1308501A72870E541D963fB8D5D58e953b03d475', token='0xC563388e2e2fdD422166eD5E76971D11eD37A466',identifier=1112222, amount=111
```

## Expected Result
- py-raiden receives SecretRequest, answers with appropriate messages
- lightclient receives secret, transfer is successful

## Actual Result
- transfer stays pending in lightclient until the Lock expires
- py-raiden keeps on retrying sending the transfer, which is ignored by the lightclient (since it knows it already)
- py-raiden never receives the SecretRequest at [_handle_sync_messages()](https://github.com/raiden-network/raiden/blob/b150d634d23218172bc635e864e4676d4689c75d/raiden/network/transport/matrix/transport.py#L1131)

Additionally, py-raiden seems to keep on retrying transfers, that the lightclient recognizes as already expired.

## Additional Infos (Optional) 
```
- py-raiden `1.1.1` as the sender of the transfer
- Chrome 86.0.
- MacOS 10.15.7
```
[raiden_0x1308501A72870E541D963fB8D5D58e953b03d475_2020-11-11T14_04_33.162Z.log](https://github.com/raiden-network/light-client/files/5524500/raiden_0x1308501A72870E541D963fB8D5D58e953b03d475_2020-11-11T14_04_33.162Z.log)
[raiden-debug_2020-11-11T14:03:07.968206.log](https://github.com/raiden-network/light-client/files/5524502/raiden-debug_2020-11-11T14.03.07.968206.log)

### LINKED ISSUE #2433: BF1 gets No route between nodes found
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 

```
{
  "task": "<TransferTask: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'lock_timeout': 30, 'identifier': 149028145071000002}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "greenlet_name": "orchestration",
  "timestamp": "2020-12-03 23:13:48.918209",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:43433/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0xe043445533B6e654CB372FfD85A0cE76d0128E85. Expected 2..: {\"message\":\"No route between nodes found.\",\"details\":\"\"}"
}
```

Fails in the transfer task
```
TransferTask: {'from': 3, 'to': 0, 'amount': 1000000000000000, 'lock_timeout': 30, 'identifier': 149028145071000002}
```

From logs of node3

```
payload: RaidenError: No route between nodes found.
      at /lc/index.js:249268:23
      at Generator.next (<anonymous>)
      at Observable._subscribe (/lc/index.js:209078:29)
      at Observable._trySubscribe (/lc/index.js:198183:25)
      at Observable.subscribe (/lc/index.js:198169:22)
      at Object.innerSubscribe (/lc/index.js:199250:23)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._innerSub (/lc/index.js:204040:50)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._tryNext (/lc/index.js:204034:14)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._next (/lc/index.js:204017:18)
      at MergeMapSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198786:18) {
    details: {}
  },
  meta: {
    tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
    target: '0xe043445533B6e654CB372FfD85A0cE76d0128E85',
    value: BigNumber { _hex: '0x038d7ea4c68000', _isBigNumber: true }
  },
  error: true
}
```
[scenario-player-run_bf1_basic_functionality_2020-12-03T23:05:40.log](https://github.com/raiden-network/light-client/files/5642861/scenario-player-run_bf1_basic_functionality_2020-12-03T23.05.40.log)

node logs

[bf1_node3_node0_4thDec2020.tar.gz](https://github.com/raiden-network/light-client/files/5642863/bf1_node3_node0_4thDec2020.tar.gz)

### LINKED ISSUE #2443: PFS8 node0 transfer to node3 expires
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
```
{
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200, 'identifier': 154894145181000002}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "greenlet_name": "orchestration",
  "timestamp": "2020-12-10 00:30:43.392009",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:37807/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x497A9851e236F051FC07EaaEe3f0334Ee85979df. Expected 200: Transfer expired."
}
```

Fails at:
`TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200, 'identifier': 154894145181000002}`

**Transfer expired.**

```
Traceback (most recent call last):
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__
return_val = self._run(*args, **kwargs)
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run
f'HTTP status code \"{resp.status_code}\" while fetching {url}. '
scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:37807/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x497A9851e236F051FC07EaaEe3f0334Ee85979df. Expected 200: Transfer expired.
```

node0 till the end apparently could not setup a webrtc channel
```
2020-12-10T00:30:43.441Z [info] Couldn't set up WebRTC dataChannel, retrying 0x3Deb22082512004757846980a573CA8C7146e261|0x497A9851e236F051FC07EaaEe3f0334Ee85979df RTC: dataChannel closed
2020-12-10T00:30:43.449Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'rtc/channel',
  payload: undefined,
  meta: { address: '0x497A9851e236F051FC07EaaEe3f0334Ee85979df' }
}
```

LockedTransfer message

```
2020-12-10T00:03:20.770Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'transfer/signed',
  payload: {
    message: {
      type: 'LockedTransfer',
      message_identifier: BigNumber { _hex: '0x017649f59839', _isBigNumber: true },
      chain_id: BigNumber { _hex: '0x05', _isBigNumber: true },
      token_network_address: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
      channel_identifier: BigNumber { _hex: '0x40e6', _isBigNumber: true },
      nonce: BigNumber { _hex: '0x03', _isBigNumber: true },
      transferred_amount: BigNumber { _hex: '0x038d7ea4c68000', _isBigNumber: true },
      locked_amount: BigNumber { _hex: '0x038d7ea4c68000', _isBigNumber: true },
      locksroot: '0x6aa8eb78e37402b633bd5a8bdb911e5847d414a133103566f19b5ed8fbdc1258',
      payment_identifier: BigNumber { _hex: '0x02264b67854d2140', _isBigNumber: true },
      token: '0x59105441977ecD9d805A4f5b060E34676F50F806',
      recipient: '0x28c91e1aaff0657E17C5D917bA483C224DDD67d7',
      lock: {
        amount: [BigNumber],
        expiration: [BigNumber],
        secrethash: '0xdc74a5fde42db3bd5af146aa28eefc64b16dc347898f2597cd19dd7427f1c0e5'
      },
      target: '0x497A9851e236F051FC07EaaEe3f0334Ee85979df',
      initiator: '0x3Deb22082512004757846980a573CA8C7146e261',
      metadata: { routes: [Array] },
      signature: '0x413f0b0755b6399c3d52599f4d2ee65b39f8ef448584ca37bf14551ded563f3d6a92c69ae33ffe0dfae2ca4f8e56e6f8c1904405da5d8fb852b1304045d113df1b'
    },
    fee: BigNumber { _hex: '0x00', _isBigNumber: true },
    partner: '0x28c91e1aaff0657E17C5D917bA483C224DDD67d7'
  },
  meta: {
    secrethash: '0xdc74a5fde42db3bd5af146aa28eefc64b16dc347898f2597cd19dd7427f1c0e5',
    direction: 'sent'
  }
}
```

We the transferExpire request action
**transfer/expire/request**
```
2020-12-10T00:30:43.376Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'transfer/expire/request',
  meta: {
    secrethash: '0xdc74a5fde42db3bd5af146aa28eefc64b16dc347898f2597cd19dd7427f1c0e5',
    direction: 'sent'
  }
}
```

**transfer/failure** action
```
2020-12-10T00:30:43.377Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'transfer/failure',
  payload: RaidenError: Transfer expired.
      at MergeMapSubscriber.project (/lc/index.js:250113:46)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._tryNext (/lc/index.js:204027:27)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._next (/lc/index.js:204017:18)
      at MergeMapSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198786:18)
      at Observable._subscribe (/lc/index.js:209058:20)
      at Observable._trySubscribe (/lc/index.js:198183:25)
      at Observable.subscribe (/lc/index.js:198169:22)
      at MergeMapOperator.module.exports.__webpack_modules__.42713.MergeMapOperator.call (/lc/index.js:203997:23)
      at Observable.subscribe (/lc/index.js:198164:31)
      at Object.innerSubscribe (/lc/index.js:199250:23) {
    details: { block: '3899169' }
  },
  meta: {
    secrethash: '0xdc74a5fde42db3bd5af146aa28eefc64b16dc347898f2597cd19dd7427f1c0e5',
    direction: 'sent'
  },
  error: true
}
```

**transfer/expire/success**
```
2020-12-10T00:30:43.392Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'transfer/expire/success',
  payload: {
    message: {
      type: 'LockExpired',
      message_identifier: BigNumber { _hex: '0x01764a0ea8b8', _isBigNumber: true },
      chain_id: BigNumber { _hex: '0x05', _isBigNumber: true },
      token_network_address: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
      channel_identifier: BigNumber { _hex: '0x40e6', _isBigNumber: true },
      nonce: BigNumber { _hex: '0x04', _isBigNumber: true },
      transferred_amount: BigNumber { _hex: '0x038d7ea4c68000', _isBigNumber: true },
      locked_amount: BigNumber { _hex: '0x00', _isBigNumber: true },
      locksroot: '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470',
      recipient: '0x28c91e1aaff0657E17C5D917bA483C224DDD67d7',
      secrethash: '0xdc74a5fde42db3bd5af146aa28eefc64b16dc347898f2597cd19dd7427f1c0e5',
      signature: '0x51dfc365086bc7bef72a0bb646f320dc185e6509353d313c05f2b6b3e234403f6d45137c9e2e7cc331dd83713b3b2e6cef098a5e35189635b25b63230f4fe5e31c'
    },
    partner: '0x28c91e1aaff0657E17C5D917bA483C224DDD67d7'
  },
  meta: {
    secrethash: '0xdc74a5fde42db3bd5af146aa28eefc64b16dc347898f2597cd19dd7427f1c0e5',
    direction: 'sent'
  }
}
```

**message/send/request**
```
2020-12-10T00:30:43.417Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'message/send/request',
  payload: {
    message: {
      type: 'LockExpired',
      message_identifier: BigNumber { _hex: '0x01764a0ea8b8', _isBigNumber: true },
      chain_id: BigNumber { _hex: '0x05', _isBigNumber: true },
      token_network_address: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
      channel_identifier: BigNumber { _hex: '0x40e6', _isBigNumber: true },
      nonce: BigNumber { _hex: '0x04', _isBigNumber: true },
      transferred_amount: BigNumber { _hex: '0x038d7ea4c68000', _isBigNumber: true },
      locked_amount: BigNumber { _hex: '0x00', _isBigNumber: true },
      locksroot: '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470',
      recipient: '0x28c91e1aaff0657E17C5D917bA483C224DDD67d7',
      secrethash: '0xdc74a5fde42db3bd5af146aa28eefc64b16dc347898f2597cd19dd7427f1c0e5',
      signature: '0x51dfc365086bc7bef72a0bb646f320dc185e6509353d313c05f2b6b3e234403f6d45137c9e2e7cc331dd83713b3b2e6cef098a5e35189635b25b63230f4fe5e31c'
    }
  },
  meta: {
    address: '0x28c91e1aaff0657E17C5D917bA483C224DDD67d7',
    msgId: '1607560243384'
  }
}
```

[scenario-player-run_pfs8_mediator_goes_offline_2020-12-09T23:54:11.log](https://github.com/raiden-network/light-client/files/5671243/scenario-player-run_pfs8_mediator_goes_offline_2020-12-09T23.54.11.log)

[pfs8_node0_node3_10Dec2020.tar.gz](https://github.com/raiden-network/light-client/files/5671245/pfs8_node0_node3_10Dec2020.tar.gz)

### PR DESCRIPTION
**Pull request by andrevmatos**
Fixes #2303 
Fixes #2352 
Fixes #2433 
Fixes #2443 

**~Short~ Description**
This ended up being larger than expected, since it involved a big transport refactoring and a lot of server and client-side debugging. Fortunately, the end result is very good from my perspective, and adds a lot of performance improvements and preemptive bugfixes:
- Presence bug is fixed: we call `matrix.setPresence` explicitly after a random time after start, which causes a new presence update event to be emitted to all clients and federated servers, refreshing our presence for the rest of the session
  - A similar call is issued whenever capabilities change, since this was the only way to trigger peers to re-fetch our profileInfo and get the up-to-date avatarUrl
- WebRTC signaling messages are send using the standard messaging epics, instead of calling the helpers directly
- Instead of the complex waiting logic we had before sending a message, now messages are always sent as soon as possible, and instead, we hold the `messageSend.success` action, which was waited for before retry loops, until some condition is met which tells us with a higher confidence the message was received, e.g. peer is online
  - Send the messages early allows it to work even if the peer appeared offline, since they would get the message anyway
- The points above allows WebRTC signaling messages and channels to be established even if peers appears offline to each other, while "waiting" for the same conditions as message success action before retrying; the result is that the channels can be now established "asynchronously" (e.g. offer sent while callee was still offline) and while peers look offline to each other
  - Because RTC channel negotiation doesn't depend on the matrix presence anymore, it becomes an additional source of truth for presences: if an RTC channel is established, we consider partner as `online` even if they look offline in matrix
  - Also, now we avoid creating RTC channels with any node we fetch presence for, and instead do it only for neighbors and target/initiator on transfer sends. Hopefully, in the future, we can also remove the later.
- When using rooms, only the lower address creates the room and invite: this streamlines this behavior with PC. While our previous did work fine, it was more prone to races and could take longer to establish a reliable on-matrix communication room.
- Batch and serialize per-address p2p messages and per-room global messages:
  - This can reduce a lot the number of parallel matrix requests, which have shown to bottleneck the transport
  - This also reduces the number of API requests needed, since batching can send multiple messages in a single request
  - Once we get rid of the rooms code and messaging, it can be made even more efficient, since `sendToDevice` can send messages of the same type to multiple recipients in a single API request
- Adds better retries, batchSize and timing data to `messageSend.success` actions and add log calls with these info after a `messageGlobalSend` request is completed.
- Retry some PFS network/server errors (not common, but seen during tests)

Most/all these changes are covered by the current tests. They're mostly under the hood (visible effect is just that transport should work more reliably), so it's hard to test by hand, but the Scenario Player should tell us.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.
2.

### CODE REVIEW

**Comment by agatsoh** [comment]
On the latest run of SP the BF4 scenarios fails due to the `Transfer expired.` exception
[scenario-player-run_bf4_multi_payments_same_node_2020-12-17T12:08:43.log](https://github.com/raiden-network/light-client/files/5710236/scenario-player-run_bf4_multi_payments_same_node_2020-12-17T12.08.43.log)


[bf4_node0_node5_17Dec2020.tar.gz](https://github.com/raiden-network/light-client/files/5710251/bf4_node0_node5_17Dec2020.tar.gz)

**Comment by agatsoh** [comment]
BF6 logs 
[scenario-player-run_bf6_stress_hub_node_2020-12-17T14:26:57.log](https://github.com/raiden-network/light-client/files/5710589/scenario-player-run_bf6_stress_hub_node_2020-12-17T14.26.57.log)


[bf6_all_10_node_logs_17Dec2020.tar.gz](https://github.com/raiden-network/light-client/files/5710604/bf6_all_10_node_logs_17Dec2020.tar.gz)

**Comment by andrevmatos** [comment]
Ok, checking the logs from BF4 and BF6 and running BF4 locally, I could confirm the BF4 failure was NOT caused by the presence issue, which seems to be fixed by the approach on this PR (:tada:)!!!

The error on BF4 was caused by a race where both LCs would create and invite the other to rooms, and then keep switching between them and not being able to get the message through.

The fix is included on this PR, and is taking the same approach as the PC and the one we use for caller/callee choice on our WebRTC: only one of the nodes in a pair (the lower address, when sorting lexically) is responsible for creating the room.

With this, ALL our supported scenarios (all but mfee) are **green** :green_heart: even with `toDevice` disabled, which was shown to definitely trigger the presence bug before!

**Comment by palango** [comment]
Regarding the failure of MFEE2 today. Here's the logs with the PFS the first nodes used. let me know if you need the other ones as well.

[Archive.zip](https://github.com/raiden-network/light-client/files/5716288/Archive.zip)

**Comment by agatsoh** [comment]
23rd December the runs were on this PR 
BF7 

[scenario-player-run_bf7_long_path_2020-12-23T01:21:16.log](https://github.com/raiden-network/light-client/files/5735143/scenario-player-run_bf7_long_path_2020-12-23T01.21.16.log)


[bf7_node0_node7_23Dec2020.tar.gz](https://github.com/raiden-network/light-client/files/5735148/bf7_node0_node7_23Dec2020.tar.gz)

**Comment by agatsoh** [comment]
24th December Failure logs:
BF7
[scenario-player-run_bf7_long_path_2020-12-24T01:21:16.log](https://github.com/raiden-network/light-client/files/5739382/scenario-player-run_bf7_long_path_2020-12-24T01.21.16.log)

[bf7_node0_node3_24Dec2020.tar.gz](https://github.com/raiden-network/light-client/files/5739383/bf7_node0_node3_24Dec2020.tar.gz)

BF6
[scenario-player-run_bf6_stress_hub_node_2020-12-24T00:55:33.log](https://github.com/raiden-network/light-client/files/5739434/scenario-player-run_bf6_stress_hub_node_2020-12-24T00.55.33.log)

[bf6_node5_node3_24Dec2020.tar.gz](https://github.com/raiden-network/light-client/files/5739435/bf6_node5_node3_24Dec2020.tar.gz)

File: raiden-ts/src/transport/epics/helpers.ts [hunk 1]
```diff
@@ -64,101 +65,87 @@ export function getRoom$(matrix: MatrixClient, roomIdOrAlias: string): Observabl
...
+        return matrix$.pipe(
+          mergeMap(async (matrix) => matrix.sendEvent(via, type, content, '')),
+          mapTo(via), // via room
+          // complete only when peer is online
+          delayWhen(constant(presence$.pipe(filter((presence) => !!presence?.payload.available)))),
+        );
+    }),
+    retryWhile(intervalFromConfig(config$), {
+      maxRetries: 3,
+      onErrors: [429, 500],
```
Comment (palango) [inline raiden-ts/src/transport/epics/helpers.ts]: Should we add `networkErrors` here as well?

File: raiden-ts/src/transport/epics/webrtc.ts [hunk 2]
```diff
@@ -130,117 +138,101 @@ async function getMatrixIceServers(matrix: MatrixClient): Promise<RTCIceServer[]
...
-        event.getSender() === sender &&
-        (event as ExtMatrixEvent).getContent()?.msgtype === 'm.notice',
+      (action) => action.meta.address === sender && action.payload.msgtype === rtcMatrixMsgType,
     ),
-    mergeMap((event) => {
+    mergeMap(function* (action) {
       try {
-        return of(decode(rtcCodecs[type], jsonParse(event.getContent()?.body)));
+        yield decode(rtcCodecs[type], jsonParse(action.payload.text));
       } catch (e) {}
```
Comment (palango) [inline raiden-ts/src/transport/epics/webrtc.ts:159]: Should we at least log something here in case of an error?

File: raiden-ts/src/transport/epics/webrtc.ts [hunk 3]
```diff
@@ -130,117 +138,101 @@ async function getMatrixIceServers(matrix: MatrixClient): Promise<RTCIceServer[]
...
+          );
+        }
+      }),
+      ignoreElements(),
+    ),
+    // when seeing an icecandidate, send it to peer
+    fromEvent<RTCPeerConnectionIceEvent>(connection, 'icecandidate').pipe(
+      pluck('candidate'),
+      takeWhile(isntNil),
+      bufferTime(10),
```
Comment (palango) [inline raiden-ts/src/transport/epics/webrtc.ts:201]: Is this seconds? Seems quite long especially when setting up the connection...

File: raiden-ts/src/transport/utils.ts [hunk 4]
```diff
@@ -107,3 +108,13 @@ export function parseCaps(caps?: string | null): Caps | undefined {
...
   return caps?.[cap] ?? CapsFallback[cap];
 }
+
+/**
+ * Return addresses sorted in lexical order
+ *
+ * @param addresses - Addresses to sort
+ * @returns Addresses sorted in lexical order
+ */
+export function getSortedAddresses<A extends [Address, ...Address[]]>(...addresses: A) {
```
Comment (palango) [inline raiden-ts/src/transport/utils.ts]: Some simple tests for this would be nice. I remember some there was some bug in this function in the PC.

File: raiden-ts/src/transport/epics/rooms.ts [hunk 5]
```diff
@@ -64,23 +60,24 @@ function inviteLoop$(
...
-      fromEvent<[MatrixEvent, RoomMember]>(matrix, 'RoomMember.membership').pipe(
-        pluck(1),
-        filter((member) => member.roomId === roomId && member.userId === userId),
-        startWith(matrix.getRoom(roomId)?.getMember(userId)),
-        map((member) => member?.membership !== 'join'),
-        distinctUntilChanged(),
+  return timer(pollingInterval, httpTimeout).pipe(
+    exhaustMap(() =>
+      defer(async () => {
+        const membership = matrix.getRoom(roomId)?.getMember(userId)?.membership;
```
Comment (palango) [inline raiden-ts/src/transport/epics/rooms.ts:66]: Do we need rate limiting error handling here?

File: raiden-ts/src/transport/epics/rooms.ts [hunk 6]
```diff
@@ -64,23 +60,24 @@ function inviteLoop$(
...
+        if (membership === 'join' || membership === 'invite') return null;
+        return matrix.invite(roomId, userId);
```
Comment (palango) [inline raiden-ts/src/transport/epics/rooms.ts:68]: as above

File: raiden-ts/src/transport/epics/rooms.ts [hunk 7]
```diff
@@ -257,31 +252,40 @@ export function matrixHandleInvitesEpic(
...
+        // found for sender in time
+        timeout(httpTimeout),
+        map((senderPresence) => ({ matrix, member, senderPresence })),
+        // on timeout error, leave invited room
+        catchError(() =>
+          defer(async () => {
+            log.info("Leaving invited room because we don't know the inviter", event);
+            return matrix.leave(member.roomId);
+          }).pipe(
+            retryWhile(intervalFromConfig(config$), { onErrors: [429] }),
```
Comment (palango) [inline raiden-ts/src/transport/epics/rooms.ts:276]: More general: In most cases we only handle 429 here. Should we also handle 500 and network errors?

File: raiden-ts/src/transport/epics/messages.ts [hunk 8]
```diff
@@ -123,26 +125,38 @@ export function matrixMessageGlobalSendEpic(
...
             'm.room.message',
             { body: getMessageBody(action.payload.message), msgtype: 'm.text' },
             '',
           );
         }),
-        retryWhile(intervalFromConfig(config$), { maxRetries: 3, onErrors: [429, 500] }),
+        timeout(config.httpTimeout),
+        retryWhile(intervalFromConfig(config$), {
+          maxRetries: 3,
+          onErrors: [429, 500, 'Timeout', 'timeout'],
```
Comment (palango) [inline raiden-ts/src/transport/epics/messages.ts]: Should we use `networkErrors` here instead of adding timeout matches manually?

File: raiden-ts/src/transport/epics/webrtc.ts [hunk 9]
```diff
@@ -164,7 +164,7 @@ function matrixWebrtcEvents$<T extends RtcEventType>(
 
 type RtcConnPair = readonly [RTCPeerConnection, RTCDataChannel];
 function isRtcConnPair(value: unknown): value is RtcConnPair {
-  return Array.isArray(value) && value.length === 2 && value[0] instanceof RTCPeerConnection;
```
Comment (palango) [inline raiden-ts/src/transport/epics/webrtc.ts]: Just out of curiosity (maybe you mentioned it Friday, but then I forgot). Why is it better to avoid `instanceof`?

File: raiden-ts/src/services/epics.ts [hunk 10]
```diff
@@ -124,7 +124,10 @@ function fetchLastIou$(
           method: 'GET',
           headers: { 'Content-Type': 'application/json' },
         },
-      ).pipe(timeout(httpTimeout)),
+      ).pipe(
+        timeout(httpTimeout),
+        retryWhile(intervalFromConfig(config$), { onErrors: [429, 500, 'timeout', 'Timeout'] }),
```
Comment (palango) [inline raiden-ts/src/services/epics.ts:129]: Same here, should we use `networkErrors`?

**Review by palango — COMMENTED** [review]
Nice PR, thanks for pushing through all those little problems. Also the walk through on Friday really helped!

That said, I left some nitpicks, but in general this is fine to merge from my side. The biggest concern (sorry for commenting on this multiple times) is that error/retry handling seems a bit inconsistent, or at least the logic isn't clear to me. But that's something we can also fix afterwards.

File: raiden-ts/src/transport/epics/helpers.ts (hunk 1 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/helpers.ts]: Yes, we should do that.

File: raiden-ts/src/transport/epics/webrtc.ts (hunk 2 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/webrtc.ts:159]: This isn't critical, but I think it'd be good, in case this starts to fail silently

File: raiden-ts/src/transport/epics/webrtc.ts (hunk 3 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/webrtc.ts:201]: No, this is millis. This isn't intended to slow down the rtc connection establishment, but instead simply batch (synchronous or asynchronous) bursts of candidates gathered or cached together, which then gets sent on the same signaling message. This was already here before, just moved it around.

File: raiden-ts/src/transport/epics/rooms.ts (hunk 5 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/rooms.ts:66]: No, the `catchError` and `timer` will loop through it and reinvite on next loop.

File: raiden-ts/src/transport/epics/rooms.ts (hunk 6 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/rooms.ts:68]: as above, no

File: raiden-ts/src/transport/epics/rooms.ts (hunk 7 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/rooms.ts:276]: Yes, Paul, I think it's worth it to unify these 429, 500 and `networkErrors` handling, I didn't want to do this in this PR, but I think it'd be easier than creating another, I'll push a commit soon.

File: raiden-ts/src/transport/epics/messages.ts (hunk 8 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/messages.ts]: Will do.

File: raiden-ts/src/transport/epics/rooms.ts (hunk 7 above)
Comment (palango) [reply raiden-ts/src/transport/epics/rooms.ts:276]: It's fine for me to do it in a follow-up.

File: raiden-ts/src/transport/epics/webrtc.ts (hunk 9 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/epics/webrtc.ts]: JS uses prototype-based inheritance, which will identity-check if the constructor of the class passed as param is in the prototype chain of the object being tested. This gives some trouble with `instanceof` when you have multiple deps version in `node_modules` on a mono-repo structure, where `instanceof` will fail if the object was created with a constructor on a different dependency folder.
Also, on this specific case, it was changed because I was mocking the `RTCPeerConnection` using a plain object, and then the `instanceof` failed.

Comment (palango) [reply raiden-ts/src/transport/epics/webrtc.ts]: Thanks, that makes sense.

**Review by palango — APPROVED** [review]
LGTM 🍾 🥳

File: raiden-ts/src/transport/utils.ts (hunk 4 above)
Comment (andrevmatos) [reply raiden-ts/src/transport/utils.ts]: Done. Rebasing.
