### PR TITLE
Fixed missing error message when connecting to main net

### LINKED ISSUE #1115: No error message when pressing connect on an unsupported network
## Steps to Reproduce
1. Switch to mainnet
2. Press connect

## Expected Result
- Warning about network not being supported

## Actual Result
- Button/label change colors and then nothing happens

### PR DESCRIPTION
**Pull request by nephix**
Fix #1115

### CODE REVIEW

File: raiden-dapp/src/components/SplashScreen.vue [hunk 1]
```diff
@@ -188,12 +195,6 @@ export default class Loading extends Vue {
     height: 48px;
   }
 
-  &__disclaimer {
-    margin: 0 auto;
-    margin-top: 180px;
-    max-width: 560px;
```
Comment (taleldayekh) [inline raiden-dapp/src/components/SplashScreen.vue]: Thank you for taking care of this. I'm just wondering why the max-width is removed? I added it to have the text break in those two lines if the window is large.

Comment (nephix) [reply raiden-dapp/src/components/SplashScreen.vue]: The text already broke, but the max width made the text appear uncentered

Comment (taleldayekh) [reply raiden-dapp/src/components/SplashScreen.vue]: Ah, ok, did not notice that. Thank you.
